### ISSUE TITLE
Gracefully handle old activity namespace

### ISSUE THREAD

**Issue by nikku** [camunda/bpmn-io-modeler#63]
* [x] detect `activiti` namespace
* [x] ask users to migrate and tell him that properties may only be edited on `camunda` namespace
* [x] migrate + reimport if the user allows it

**Comment by ricardomatias** [comment]
Activity: http://activiti.org/bpmn
Camunda: http://camunda.org/schema/1.0/bpmn

**Comment by gimbel** [comment]
There are properties in your diagram which use the old version of the Camunda namespace (http://activiti.org/bpmn).

Do you want to convert it to the new namespace (http://camunda.org/schema/1.0/bpmn)? 

Otherwise you will not be able to edit your properties with this modeler.

The new namespace works with Camunda BPM version 7.4.0, 7.3.3, 7.2.6 and onwards.
